1 terraform azure vm bastion
cloud-native-toolkit/terraform-azure-vm-bastion pull request #2
Opened 2022-06-03 08:03 UTC by hemang-ibm

Added azure vm bastion host module.

@rich-ehrhardt  
Please review the code and update workflow folder as per azure provider before merge.

2022-06-07 06:43 UTC, rich-ehrhardt requested changes
Missing `test/stages/provider.tf`. See `https://github.com/cloud-native-toolkit/terraform-azure-lb/blob/main/test/stages/provider.tf` for example.

Can you use the subnet module (azure-vnet-subnets) within main.tf to also set ACL?

2022-06-10 05:40 UTC, hemang-ibm commented
> Missing `test/stages/provider.tf`. See `https://github.com/cloud-native-toolkit/terraform-azure-lb/blob/main/test/stages/provider.tf` for example.
> 
> Can you use the subnet module (azure-vnet-subnets) within main.tf to also set ACL?

@rich-ehrhardt 

Have implemented changes suggested by you to use existing subnet module in bastion vm host module with subnet_name pass as a parameter.

code changes has been committed. But we are getting error for test case execution failed in "eastus" location as below.

***Error: waiting for creation/update of Bastion Host: (Name "ahm_vm_bastion" / Resource Group "vpc-test"): Code="GatewayAllocationFailed" Message="Compute allocation failed. Please retry later." Details=[]***


But test case is successfully get executed in "central india" and "west europe".

Please guide for location specific issue in test case execution.

2022-06-17 06:01 UTC, hemang-ibm commented
@rich-ehrhardt  All tests is successfully executed. Please review the branch and approve the PR.

2022-06-20 23:22 UTC, rich-ehrhardt approved these changes

2022-07-04 01:35 UTC, merged